spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jooq:
    sql-dialect: POSTGRES
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      auto-startup: ${KAFKA_ENABLED:false}

server:
  port: ${PORT:8080}

logging:
  level:
    ru.zahaand.lifesync: INFO
    root: INFO

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
